### ISSUE TITLE
Use of libb64 for vorbis picture support

### ISSUE THREAD

**Issue by djmattyg007** [khenriks/mp3fs#43]
Hi there. I recently resurrected and updated the Arch User Repository package for mp3fs: https://aur.archlinux.org/packages/mp3fs-git/

Unfortunately I've had to disable vorbis picture support because of the lack of a package for libb64 in Arch. Is it possible to use the base64 encoding/decoding functions that are part of glibc instead?

**Comment by quarterpounder** [comment]
The glibc base64 decoding support is _very_ low-level. libb64 on the other hand is by far more sophisticated and speedy. May it is possible to get libb64 into AUR.

**Comment by khenriks** [comment]
I've decided to just embed base64 routines directly in the code to avoid this dependency.
