### ISSUE TITLE
Memory Leak - when mounting mp3fs from SMB Mount

### ISSUE THREAD

**Issue by SeanOBoyle** [khenriks/mp3fs#46]
Looks like there's a memory leak with mp3fs. This is resulting in mp3fs being killed by the kernel.

Setup:
Ubuntu machine with an mp3fs path shared via smb.
SMB mounted on an OSX Machine.
OSX Machine using iTunes to scan media.

When doing a scan ("Add to Library") of the entire shared drive from iTunes, the memory usage on the Ubuntu server 'mp3fs' process climbs to 100% and then mp3fs is killed by the kernel:
Jan  7 19:21:05 foo kernel: [27553.533658] Out of memory: Kill process 746 (mp3fs) score 935 or sacrifice child
Jan  7 19:21:05 foo kernel: [27553.533660] Killed process 746 (mp3fs) total-vm:15625292kB, anon-rss:7413504kB, file-rss:0kB

Version:
$ mp3fs --version
mp3fs version: 0.91
LAME library version: 3.99.5
FLAC library version: 1.3.0
FUSE library version: 2.9.2
fusermount version: 2.9.2
using FUSE kernel interface version 7.19

OS: 
Ubuntu 14.04.3 LTS
$ uname -a
Linux foo 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by camelreef** [comment]
I can confirm that. Up-to-date Ubuntu and a Samba share to give access to an iTunes on Windows.

mp3fs --version
mp3fs version: 0.91
LAME library version: 3.99.5
FLAC library version: 1.3.1
FUSE library version: 2.9.4
fusermount version: 2.9.4
using FUSE kernel interface version 7.19

Samba Version: 2:4.1.17+dfsg-4ubuntu3.3

**Comment by khenriks** [comment]
Since this specifically affects Samba, it could be the same issue as #57. Does it still happen with the latest commit from the master branch?

**Comment by khenriks** [comment]
Since there's no updates, I'll assume this is resolved.
