### ISSUE TITLE
Question: libb64

### ISSUE THREAD

**Issue by dcrdev** [khenriks/mp3fs#47]
So I'm trying to compile from source and am rceiving the following error during configuration:

"libb64-dev must be installed for Ogg Vorbis picture support"

I'm using Fedora, which has no libb64 package - so I tried to compile that as well. I copied the resulting base64 executable to /usr/local/bin and the b64 header files to /usr/include. I'm still receiving the same error whilst configuring, am I missing something?

Thanks,

**Comment by djmattyg007** [comment]
It appears to be a Debian thing. See my issue, #43.

**Comment by khenriks** [comment]
I've decided to just embed base64 routines directly in the code to avoid this dependency.
