### ISSUE TITLE
Large memory footprint persisted when no longer in use

### ISSUE THREAD

**Issue by brianmarx** [khenriks/mp3fs#51]
Hello and thanks for this nifty transcoderfs!

I have mine set up to be visible via Apache's default directory viewer. (please don't /r/opendirectories me)

A friend viewed and listened to a single song, but many times. From the access logs it appears he seeked and restarted, and listened for variable lengths each time. Nothing showed in the error log.

Several hours later, mp3fs was still listed as taking around 500 mb of memory, until i un- and remounted it (back to normal now!). it was also still using several threads. Seems it did not properly drop and reload the file when apache re-served it. 

thanks again!

**Comment by khenriks** [comment]
Can you give me more details on the setup. Which version of apache was this? Leaking the file handles could cause this, but I'm not sure if that's what's taking place.

**Comment by khenriks** [comment]
Another useful bit of debugging info: does restarting Apache also cause the memory to be recovered?

**Comment by khenriks** [comment]
Closing for lack of information.
