### ISSUE TITLE
Planning to extend file format support

### ISSUE THREAD

**Issue by nschlia** [khenriks/mp3fs#56]
I just cloned the mp3fs because it exactly does what I need for my project. I intend to expand the format support to a lot more, including video formats using the ffmpeg library. I'll still have to review if this is possible but I think it will.

Please drop me a line when you are interested.

**Comment by nschlia** [comment]
Answering my own post... Replaced encoding/decoding with FFMPEG API. See my fork. Still not complete, mp4 handling far from perfect, video not supported... But first step done.

**Comment by beren12** [comment]
plain old .wav would be good as well, pretty sure iTunes can just transcode it into mp4 for me

**Comment by nschlia** [comment]
FFmpegs has grown to big and independent project. No way to merge changes back, therefore this request can be closed.
