### ISSUE TITLE
please clarify licensing

### ISSUE THREAD

**Issue by fabiangreffrath** [khenriks/mp3fs#62]
Hi there,

apparently, the mp3fs project is licensed under different licenses: GPL3+ for the code and GFDL for the docs - which is already a pretty unfortunate combination: 
https://en.wikipedia.org/wiki/GNU_Free_Documentation_License#GPL_incompatible_in_both_directions

Furthermore, it seems that only 3 files are licensed under GFDL: NEWS, README.md and mp3fs.1.txt. Only the first file, NEWS, contains the GFDL license blurb with the "no invariant sections" clause, which would make the license DFSG-compatible.

So:
 - please reconsider the choice of the GFDL for the project's documentation altogether,
 - please clarify if the GFDL with the "no invariant sections" clause applies to all files.

Thank you very much!

**Comment by khenriks** [comment]
Thanks for bringing this to my attention. I didn't realize how much of a mess it was, and your link prompted me to have a bit of looking around, including at the DFSG.  I've opted to dual-license all documentation under GFDL 1.3+ (explicitly specifying no invariant sections) and GPL 3+.

**Comment by fabiangreffrath** [comment]
Great, thanks for this! I'd like to bring this to the attention of @nschlia, the author of ffmpegfs, i.e. a derived work.

**Comment by nschlia** [comment]
Great! I'll incorporate the license change into my fork as soon as it's available.

**Comment by nschlia** [comment]
Update license on my side with https://github.com/nschlia/ffmpegfs/commit/a3bfb1a51579a3320616bfed23d9eec251077b9d

Thanks a lot!
