### ISSUE TITLE
Square brackets in filename issue

### ISSUE THREAD

**Issue by RobMeerwijk** [khenriks/mp3fs#66]
Hi, I found an issue in mp3fs version 1.1 that I never experienced in the debian package (0.91). If a filename has a '[' or a ']' in it, the file shows up (e.g. in rsync) but cannot be listed, copied or accessed. Lots of media flac files have these brackets. 

rsync output: 
_file has vanished: "/volume1/mp3fs/Alessandro Safina/Insieme a Te [14 Tracks]/09 Alessandro Safina Insieme a Te.mp3"_

I reverted to version 1.0. This release handles the filenames without problem.  

Thanks for the great work. And now using docker I run mp3fs directly on the NAS without the need of an external raspberry pi for transcoding!

**Comment by khenriks** [comment]
Wow, that's a pretty embarrassing error. Sorry about that. I think I have a fix, and I've just pushed it to Docker with the `1.1-fix66` tag. Can you try it out and see if it works for you?

**Comment by RobMeerwijk** [comment]
fixed! and i don't think it is embarrasing. making an error proves that you are only human! thanks for the fix!

**Comment by khenriks** [comment]
I'm glad it worked for you! I also made a new release (1.1.1) and pushed it to Docker hub to make the fix official.
