### ISSUE TITLE
Read and provide embedded pictures from FLAC to MP3

### ISSUE THREAD

**Issue by viertelb** [khenriks/mp3fs#68]
I just realized `mp3fs` does not provide the pictures I embedded in my `flac`. It never occured to me, probably, because in the past I copied all other files also, which often provided a `folder.jpg` with the album.

But since I moved more and more to `flac` I even used the command line to add a picture to each file and removed the file from the folder: 

`metaflac --import-picture-from="$FILEPATH" "$f"`

I did this because in Linux, version `2.4.2.` of `easytag` broke the `flac`, when adding a picture to a track. 

Now, with my command, the `flacs` play well and show the album cover. But `mp3fs` seems not to copy this. This brought me to question if I do use the right command, since it is lacking a reference to "what" actually is the typ of the picture (album, artist, are there more?).

But if `mp3fs` is currently not reading embedded pictures, I wanted to suggest to add this feature.

**Comment by khenriks** [comment]
What software are you using to play the MP3s? It's possible that it might not be reading the picture even though it's there.

`mp3fs` does preserve the picture in the output MP3s. You should be able to verify this by comparing the resulting MP3 size from a source FLAC with no picture and the same FLAC with a picture added to it.

**Comment by viertelb** [comment]
Logitech Media Server. I am sorry I did not check this more thoroughly before posting. **The files contain the cover** but in the case of a FLAC that was converted to mp3 it is not displayed by the server. 

**This is most probably not the issue of mp3fs.** I will nevertheless post some output here because I don't understand why the files would be handled differently. First file originally mp3, second one converted from flac. First file does show artwork, second file does not. Both do show artwork in Tauon Music Box player. Of course I will bring this up on the server's forum.

```
Input #0, mp3, from '01 1, 2, 3.mp3':
  Metadata:
    title           : 1, 2, 3
    artist          : 4 Lyn
    album           : 4Lyn
    genre           : Rock
    composer        : Ron Clauss/Bjorn Dussler/Sascha Carrilho/Benjamin Eckebrecht
    track           : 01/15
    disc            : 01/01
    encoded_by      : iTunes 10.7
    date            : 2011
  Duration: 00:01:46.45, start: 0.000000, bitrate: 257 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 256 kb/s
    Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 600x588 [SAR 1:1 DAR 50:49], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Other
```


```
Input #0, mp3, from '01 - Fear Inoculum.mp3':
  Metadata:
    encoder         : MP3FS
    title           : Fear Inoculum
    artist          : Tool
    album           : Fear Inoculum
    date            : 2019
    track           : 01
    genre           : Metal
    TLEN            : 620101
  Duration: 00:10:20.15, start: 0.000000, bitrate: 194 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 192 kb/s
    Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1500x1500 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)
```

**Comment by viertelb** [comment]
I discussed the issue in the [forum](https://forums.slimdevices.com/showthread.php?115001-LMS-does-not-show-artwork-of-mp3-that-was-converted-from-flac&p=1030911#post1030911) of LMS. We seem to have pointed the problem to LMS not being able to read the artwork from ID3v2.4.

I suspect `mp3fs` is automatically converting flac to ID3v2.4, right?

**Comment by khenriks** [comment]
Yeah, that's right. I suspect you probably will need #9 to be fixed to make this work for you.

**Comment by viertelb** [comment]
The bug is in the other software and due to the CRC checksum. The guys are already working on it.

 https://forums.slimdevices.com/showthread.php?115010-Should-LMS-read-metadata-from-ID3v2-4&goto=newpost

**Comment by viertelb** [comment]
Just a heads-up. Probably, everything is fine and there is nothing to do for you. I though you should know just in case.

The fix in the other software is due to extended header because of the CRC in your tag.

https://github.com/andygrundman/Audio-Scan/pull/12

**Comment by khenriks** [comment]
Ok, I'll just close this now then.
